const Router = require('express');
const router = new Router();
const exercisesRouter = require('./exercises/exercisesRouter');
const exercisesInfoRouter = require('./exercises/exercisesInfoRouter');
const patternRouter = require('./pattern/patternRouter');
const patternExercisesRouter = require('./pattern/patternExercisesRouter');
const patternWorkoutExercisesRouter = require('./pattern/patternWorkoutExercisesRouter');
const userPatternRouter = require('./pattern/userPatternRouter');
const muscleGroupsRouter = require('./muscleGroupsRouter');
const usersRouter = require('./usersRouter');
const workoutRouter = require('./workoutRouter');
const workoutExercisesRouter = require('./workoutExercisesRouter');
const rolesRouter = require('./rolesRouter');
const userExercisesRouter = require('./userExercisesRouter');
const calendarEventsRouter = require('./calendarEvents/calendarEventsRouter');
const calendarTypeEventsRouter = require('./calendarEvents/calendarTypeEventsRouter');

router.use('/users', usersRouter);
router.use('/muscle_groups', muscleGroupsRouter);
router.use('/roles', rolesRouter);
router.use('/exercises', exercisesRouter);
router.use('/exercise_info', exercisesInfoRouter);
router.use('/patterns', patternRouter);
router.use('/pattern_exercises', patternExercisesRouter);
router.use('/pattern_workout_exercises', patternWorkoutExercisesRouter);
router.use('/user_patterns', userPatternRouter);
router.use('/workout', workoutRouter);
router.use('/user_exercises', userExercisesRouter);
router.use('/workout_exercises', workoutExercisesRouter);
router.use('/calendar_events', calendarEventsRouter);
router.use('/calendar_type_events', calendarTypeEventsRouter);

module.exports = router;
