export const CALENDAR = {
	WEEKS: [
		{ id: 1, name: 'Понедельник', shortName: 'Пн', enName: 'Mon' },
		{ id: 2, name: 'Вторник', shortName: 'Вт', enName: 'Tue' },
		{ id: 3, name: 'Среда', shortName: 'Ср', enName: 'Wed' },
		{ id: 4, name: 'Четверг', shortName: 'Чт', enName: 'Thu' },
		{ id: 5, name: 'Пятница', shortName: 'Пт', enName: 'Fri' },
		{ id: 6, name: 'Суббота', shortName: 'Сб', enName: 'Sat' },
		{ id: 7, name: 'Воскресенье', shortName: 'Вс', enName: 'Sun' },
	],
	MONTHS: [
		{ id: 1, name: 'Январь', enName: 'January' },
		{ id: 2, name: 'Февраль', enName: 'February' },
		{ id: 3, name: 'Март', enName: 'March' },
		{ id: 4, name: 'Апрель', enName: 'April' },
		{ id: 5, name: 'Май', enName: 'May' },
		{ id: 6, name: 'Июнь', enName: 'June' },
		{ id: 7, name: 'Июль', enName: 'July' },
		{ id: 8, name: 'Август', enName: 'August' },
		{ id: 9, name: 'Сентябрь', enName: 'September' },
		{ id: 10, name: 'Октябрь', enName: 'October' },
		{ id: 11, name: 'Ноябрь', enName: 'November' },
		{ id: 12, name: 'Декабрь', enName: 'December' },
	],
};
